# action.yml
name: 'AI powered Automatic PR Body Generation AI Model'
description: 'Automatically generates a PR body based on the PR content using openai'
branding:
  icon: 'git-pull-request'
  color: 'blue'
inputs:
  OPENAI_API_KEY:  # id of input
    required: true
  OPENAI_MODEL:
    required: false
    default: 'gpt-3.5-turbo'
runs:
  using: "composite"
  steps:
    - run: gh pr view ${{ github.head_ref }} --json body,id >> pr_data.txt
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
    - run: gh pr diff ${{ github.head_ref }} >> pr_diff.txt
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash
    - run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - id: generate_body
      run: python ${{ github.action_path }}/main.py pr_diff.txt --output-file pr_body.txt --pr-file pr_data.txt
      shell: bash
      env: 
        OPENAI_API_KEY: ${{inputs.OPENAI_API_KEY}}
        OPENAI_MODEL: ${{inputs.OPENAI_MODEL}}
    - run: gh pr edit ${{ github.head_ref }} -F pr_body.txt
      env:
        GITHUB_TOKEN: ${{ github.token }}
      shell: bash
